# Generated by Django 3.0.5 on 2021-01-06 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import musicmaps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comments', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='musicmaps.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField()),
                ('artists', models.CharField(max_length=100)),
                ('album_cover', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MusicMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', djongo.models.fields.ArrayField(model_container=musicmaps.models.Image)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('open_range', models.IntegerField(choices=[(0, 'Public'), (1, 'Follow'), (2, 'Friends'), (3, 'Friends of Friends'), (4, 'Private')])),
                ('comments_on', models.BooleanField()),
                ('location', djongo.models.fields.EmbeddedField(model_container=musicmaps.models.Location)),
                ('street_address', models.CharField(max_length=200)),
                ('building_number', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('comments', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='musicmaps.Comment')),
                ('memorize_users', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='memorize_users', to=settings.AUTH_USER_MODEL)),
                ('playlist', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='musicmaps.Music')),
            ],
            options={
                'ordering': ('date_updated',),
            },
        ),
    ]
